contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: 8dfc4c78-6835-4e51-8aaa-ce7852cc8049
    propagationLabels:
    - all
    toServerVersion: ""
id: 23621c27-b05b-4630-8017-d6f1c2b4a15e
inputs:
- description: ""
  key: IP
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: DeviceName
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: FileName
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: DeviceID
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: FileMd5
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: FileSha256
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: FileSha1
  playbookInputQuery: null
  required: false
  value: {}
name: MDE - Host Advanced Hunting For Powershell Executions
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 648e2b21-92a4-4d4b-8bbc-7d7ff22f8b9c
      iscommand: false
      name: ""
      version: -1
    taskid: 648e2b21-92a4-4d4b-8bbc-7d7ff22f8b9c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": -1290,
          "y": 60
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 562148e8-b2c4-4ee4-8020-0b03dcfa808c
      iscommand: false
      name: Process Analysis
      type: title
      version: -1
    taskid: 562148e8-b2c4-4ee4-8020-0b03dcfa808c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -620,
          "y": 375
        }
      }
  "4":
    evidencedata:
      customfields: {}
      description:
        simple: Microsoft Defender For Endpoint - Results on Process Details query
          in Advanced Hunting feature.
      tags:
        simple: Process Details
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      file_name:
        simple: ${inputs.FileName}
      query_purpose:
        simple: process_details
      sha1:
        simple: ${inputs.FileSha1}
      sha256:
        simple: ${inputs.FileSha256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Process investigation. By selecting a “query_purpose” argument,
        a designated query template will be used.
      id: 35f0f113-8779-4f42-881f-7238de9f21ff
      iscommand: true
      name: Get process details by hash or filename
      script: '|||microsoft-atp-advanced-hunting-process-details'
      type: regular
      version: -1
    taskid: 35f0f113-8779-4f42-881f-7238de9f21ff
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -620,
          "y": 510
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: MicrosoftATP.HuntProcessDetails.Result.process_details
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "6"
      - "7"
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a60df698-069f-494d-8f39-830b4dd976e5
      iscommand: false
      name: Any events of execution or association to process?
      type: condition
      version: -1
    taskid: a60df698-069f-494d-8f39-830b4dd976e5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -620,
          "y": 670
        }
      }
  "6":
    evidencedata:
      customfields: {}
      description:
        simple: Microsoft Defender For Endpoint - Results on searching additional
          devices associated with this File Sha1
      tags:
        simple: Multi Affected Devices
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      file_hash:
        simple: ${inputs.FileSha1}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get a collection of machines related to a given file SHA1 hash.
      id: 18b15d86-3087-44c3-8b15-8b8a606fc4d7
      iscommand: true
      name: List All Related Endpoints for this file
      script: '|||microsoft-atp-get-file-related-machines'
      type: regular
      version: -1
    taskid: 18b15d86-3087-44c3-8b15-8b8a606fc4d7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -850,
          "y": 860
        }
      }
  "7":
    evidencedata:
      customfields: {}
      description:
        simple: Microsoft Defender For Endpoint - Results on Unsigned Powershell query
          in Advanced Hunting feature.
      tags:
        simple: cmd###powershell
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      device_id:
        complex:
          root: inputs.DeviceID
          transformers:
          - operator: uniq
      device_name:
        complex:
          root: inputs.DeviceName
          transformers:
          - operator: uniq
      query_purpose:
        simple: powershell_execution_unsigned_files
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Process investigation. By selecting a “query_purpose” argument,
        a designated query template will be used.
      id: 0a74529c-7aa3-4021-8cfe-a2b7e9a7d070
      iscommand: true
      name: Check for any unsigned executions by Powershell?
      script: '|||microsoft-atp-advanced-hunting-process-details'
      type: regular
      version: -1
    taskid: 0a74529c-7aa3-4021-8cfe-a2b7e9a7d070
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -400,
          "y": 860
        }
      }
  "8":
    evidencedata:
      customfields: {}
      description:
        simple: Microsoft Defender For Endpoint - Results on Powershell Execution
          query in Advanced Hunting feature.
      tags:
        simple: powershell###cmd
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "20"
    note: false
    quietmode: 0
    scriptarguments:
      device_id:
        complex:
          root: inputs.DeviceID
          transformers:
          - operator: uniq
      query_purpose:
        simple: process_excecution_powershell
      sha1:
        complex:
          root: inputs.FileSha1
      sha256:
        complex:
          root: inputs.FileSha256
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Process investigation. By selecting a “query_purpose” argument,
        a designated query template will be used.
      id: af5b02bc-6d1a-425b-82a8-1ab3764b5046
      iscommand: true
      name: Check for any Powershell Execution
      script: '|||microsoft-atp-advanced-hunting-process-details'
      type: regular
      version: -1
    taskid: af5b02bc-6d1a-425b-82a8-1ab3764b5046
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 30,
          "y": 860
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      device_id:
        simple: ${inputs.DeviceID}
      query_purpose:
        simple: encoded_commands
      sha256:
        simple: ${inputs.FileSha256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Detects network connections. By selecting a “query_purpose” argument,
        a designated query template will be used.
      id: bb544534-ae2f-4666-8933-eceaa7a095b8
      iscommand: true
      name: Was there PowerShell with Encoded command?
      script: '|||microsoft-atp-advanced-hunting-network-connections'
      type: regular
      version: -1
    taskid: bb544534-ae2f-4666-8933-eceaa7a095b8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 30,
          "y": 1210
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: MicrosoftATP.HuntProcessDetails.Result.powershell_execution_unsigned_files
          operator: isNotEmpty
        - left:
            iscontext: true
            value:
              simple: MicrosoftATP.HuntProcessDetails.Result.process_excecution_powershell
          operator: isNotEmpty
      label: "yes"
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c6c4e4fd-8b70-4eed-8a54-6ce435114fdd
      iscommand: false
      name: Any results?
      type: condition
      version: -1
    taskid: c6c4e4fd-8b70-4eed-8a54-6ce435114fdd
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -400,
          "y": 1380
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.FileSha256
          operator: isNotEmpty
          right:
            value: {}
        - left:
            iscontext: true
            value:
              simple: inputs.FileSha1
          operator: isNotEmpty
      label: "yes"
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 47dea48f-7acf-4215-8b27-bb5649f647fb
      iscommand: false
      name: Is file exist?
      type: condition
      version: -1
    taskid: 47dea48f-7acf-4215-8b27-bb5649f647fb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -1290,
          "y": 205
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1af5254e-94d5-4d08-8788-4d15c735765a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 1af5254e-94d5-4d08-8788-4d15c735765a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -620,
          "y": 1920
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      appendTags:
        simple: "true"
      tags:
        complex:
          root: CommandlineVerdict
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: fbb8c07a-0efb-4c52-8ef2-f12e58c9ffdd
      iscommand: true
      name: Update the commandline verdict tag
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: fbb8c07a-0efb-4c52-8ef2-f12e58c9ffdd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -170,
          "y": 1730
        }
      }
  "18":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: MicrosoftATP.FileMachine.Machines.ID
          operator: isNotEqualString
          right:
            iscontext: true
            value:
              simple: inputs.DeviceID
      label: "yes"
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eb9661f8-947d-458f-8729-576a3f61cc05
      iscommand: false
      name: Are there any more affected devices?
      type: condition
      version: -1
    taskid: eb9661f8-947d-458f-8729-576a3f61cc05
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -850,
          "y": 1030
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      appendTags:
        simple: "true"
      tags:
        simple: Multi affected Devices
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 74db96f3-8ba4-484f-848b-a801bbce731c
      iscommand: true
      name: Update the "Multi affected Devices" tag
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 74db96f3-8ba4-484f-848b-a801bbce731c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -1060,
          "y": 1220
        }
      }
  "20":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: MicrosoftATP.HuntProcessDetails.Result.process_excecution_powershell
          operator: isNotEmpty
      label: "yes"
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c83fdfc4-ed42-4c2f-8e8a-a1a1807e9664
      iscommand: false
      name: Any PowerShell executions?
      type: condition
      version: -1
    taskid: c83fdfc4-ed42-4c2f-8e8a-a1a1807e9664
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 30,
          "y": 1020
        }
      }
  "23":
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      Commandline:
        complex:
          accessor: ProcessCommandLine
          root: MicrosoftATP.HuntProcessDetails.Result.process_excecution_powershell
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "This playbook takes the command line from the alert and performs
        the following actions:\n- Checks for base64 string and decodes if exists\n-
        Extracts and enriches indicators from the command line\n- Checks specific
        arguments for malicious usage \n\nAt the end of the playbook, it sets a possible
        verdict for the command line, based on the finding:\n1. Indicators found in
        the command line\n2. Found AMSI techniques\n3. Found suspicious parameters\n4.
        Usage of malicious tools\n5. Indication of network activity"
      id: 72f197cb-9a5a-4ed5-8b11-4e9885a3d3c2
      iscommand: false
      name: Command-Line Analysis
      playbookId: Command-Line Analysis
      type: playbook
      version: -1
    taskid: 72f197cb-9a5a-4ed5-8b11-4e9885a3d3c2
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -170,
          "y": 1550
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "14_16_#default#": 0.11,
      "15_16_#default#": 0.12,
      "15_3_yes": 0.31,
      "18_16_#default#": 0.2,
      "20_14_#default#": 0.26,
      "5_16_#default#": 0.14,
      "5_7_yes": 0.7
    },
    "paper": {
      "dimensions": {
        "height": 1925,
        "width": 1700,
        "x": -1290,
        "y": 60
      }
    }
  }
