contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
description: 'This Playbook handles a false-positive incident closure for Microsoft defender for endpoint '
id: MDE - False Positive Incident Handling
inputs:
- description: 'XSOAR Investigation IDs to be closed '
  key: DupAlertIDsToBeClosed
  playbookInputQuery:
  required: false
  value: {}
- description: Add comment to close an incident on the Microsoft Defender For Endpoint side
  key: Comment
  playbookInputQuery:
  required: false
  value:
    simple: 'XSOAR Incident #${incident.id}'
- description: |-
    Provide a reason for closing the incident. Please choose on of the following suggestions:
    "NotAvailable"/"Apt,Malware"/"SecurityPersonnel"/"SecurityTesting"/"UnwantedSoftware"/"Other"
  key: Reason
  playbookInputQuery:
  required: false
  value: {}
- description: Choose From - "Unknown" / "TruePositive" / "FalsePositive"
  key: Classification
  playbookInputQuery:
  required: false
  value: {}
- description: Specify the approving tag name for found indicators.
  key: AllowTag
  playbookInputQuery:
  required: false
  value: {}
- description: |-
    Indicates if automatic un-isolation is allowed
        True/False
  key: AutoUnisolation
  playbookInputQuery:
  required: false
  value: {}
- description: |-
    Determine if the duplicate incidents should be closed as well in Microsoft Defender Instance.
    The playbook will look for the world "Close" in this input.
  key: CloseDuplicate
  playbookInputQuery:
  required: false
  value: {}
name: MDE - False Positive Incident Handling
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '51'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 8b0086d0-9ebb-4369-8321-36545b6dada6
      iscommand: false
      name: ''
      version: -1
      description: ''
    taskid: 8b0086d0-9ebb-4369-8321-36545b6dada6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 110,
          "y": -220
        }
      }
  '1':
    id: '1'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      id:
        complex:
          root: inputs.DupAlertIDsToBeClosed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: |-
        Searches Demisto incidents.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 6fd207d1-791f-4b90-850b-a28c922534b3
      iscommand: false
      name: Retrieve MSDE alerts ID based on XSOAR investigation
      scriptName: SearchIncidentsV2
      type: regular
      version: -1
    taskid: 6fd207d1-791f-4b90-850b-a28c922534b3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -100,
          "y": 1170
        }
      }
  '2':
    id: '2'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      alert_id:
        complex:
          accessor: alertid
          root: foundIncidents.CustomFields
          transformers:
          - args:
              item:
                iscontext: true
                value:
                  simple: incident.alertid
            operator: append
      classification:
        simple: ${inputs.Classification}
      comment:
        simple: ${inputs.Comment}
      determination:
        simple: ${inputs.Reason}
      status:
        simple: Resolved
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Update the properties of an alert entity.
      id: 5d72a24f-10c7-482a-816b-2fcda6abc292
      iscommand: true
      name: Resolve MSDE Alert
      script: '|||microsoft-atp-update-alert'
      type: regular
      version: -1
    taskid: 5d72a24f-10c7-482a-816b-2fcda6abc292
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 120,
          "y": 1350
        }
      }
  '3':
    id: '3'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 3c963ac6-062d-43ad-82d3-e32d2345e793
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 3c963ac6-062d-43ad-82d3-e32d2345e793
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 120,
          "y": 1665
        }
      }
  '4':
    id: '4'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 95e97d87-0448-492c-8170-0ec11c604b99
      iscommand: false
      name: Unisolate host
      type: title
      version: -1
      description: ''
    taskid: 95e97d87-0448-492c-8170-0ec11c604b99
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -120,
          "y": 70
        }
      }
  '5':
    id: '5'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc:
      body:
        simple: Approve unisolation
      cc:
      format: ''
      methods: []
      replyOptions:
      - Yes
      - No
      subject:
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#default#':
      - '8'
      Yes:
      - '12'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 82c575e9-5484-4d95-8728-6cd14c71d448
      iscommand: false
      name: Approve unisolation
      description: Approve unisolation
      type: condition
      version: -1
    taskid: 82c575e9-5484-4d95-8728-6cd14c71d448
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -410,
          "y": 380
        }
      }
  '7':
    id: '7'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      closeReason:
        simple: ${inputs.Reason}
      id:
        complex:
          accessor: id
          root: foundIncidents
          transformers:
          - args:
              item:
                iscontext: true
                value:
                  simple: incident.id
            operator: append
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: e02da1ef-4f9b-48f0-85e3-b035227d72c2
      iscommand: true
      name: Close  XSOAR incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: e02da1ef-4f9b-48f0-85e3-b035227d72c2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 120,
          "y": 1515
        }
      }
  '8':
    id: '8'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '53'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 3bfba053-05d1-4bb9-8a41-c1815043ab44
      iscommand: false
      name: False positive Incident closing
      type: title
      version: -1
      description: ''
    taskid: 3bfba053-05d1-4bb9-8a41-c1815043ab44
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -120,
          "y": 725
        }
      }
  '9':
    id: '9'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: ada72dde-d968-4766-8009-b3f6eff1c1e2
      iscommand: false
      name: Allow indicators
      type: title
      version: -1
      description: ''
    taskid: ada72dde-d968-4766-8009-b3f6eff1c1e2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 560,
          "y": 70
        }
      }
  '12':
    id: '12'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ''
      iscommand: false
      max: 100
      scriptArguments:
        Device_id:
          simple: ${MicrosoftATP.Machine.ID}
      wait: 1
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      Device_id:
        simple: ${Endpoint.ID}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ''
      description: This playbook will auto unisolate endpoints through Microsoft Defender For Endpoint by using Hostname, IP, or Device ID associated with the asset you wish to block.
      id: 91c35cf4-1226-47e9-8c89-037e4055280f
      iscommand: false
      name: Microsoft Defender For Endpoint - Unisolate Endpoint
      playbookId: Microsoft Defender For Endpoint - Unisolate Endpoint
      type: playbook
      version: -1
    taskid: 91c35cf4-1226-47e9-8c89-037e4055280f
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -120,
          "y": 550
        }
      }
  '14':
    form:
      description: ''
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ''
        gridcolumns: []
        id: '0'
        label: ''
        labelarg:
          simple: Mark IOCs to be approved
        options: []
        optionsarg:
        - simple: ${incident.filesha256}
        placeholder: ''
        readonly: false
        required: false
        tooltip: ''
        type: multiSelect
      sender: ''
      title: Indicators to Allow
      totalanswers: 0
    id: '14'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc:
      body:
      cc:
      format: ''
      methods: []
      subject:
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#none#':
      - '68'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c45a1727-d309-446d-850b-b9fffb2dfc1e
      iscommand: false
      name: Choose the marked IOC to be added to approve list
      description: Choose the needed hashes (sh256) to be approved on your EDR and will be tagged in TI.
      type: collection
      version: -1
    taskid: c45a1727-d309-446d-850b-b9fffb2dfc1e
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 560,
          "y": 200
        }
      }
  '15':
    id: '15'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    quietmode: 0
    scriptarguments:
      indicatorsValues:
        simple: ${Indicators to block.Questions.0}
      tags:
        simple: ${inputs.AllowTag}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.indicators
      id: 81ac51cd-e033-40c6-82f2-95ba8a9468ab
      iscommand: true
      name: Tag Indicators
      script: Builtin|||setIndicators
      type: regular
      version: -1
    taskid: 81ac51cd-e033-40c6-82f2-95ba8a9468ab
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 340,
          "y": 550
        }
      }
  '16':
    id: '16'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '53'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 6950430d-209b-4dee-8c7c-7c9aa063e2fa
      iscommand: false
      name: Done approving indicators

      type: title
      version: -1
      description: ''
    taskid: 6950430d-209b-4dee-8c7c-7c9aa063e2fa
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 560,
          "y": 725
        }
      }
  '18':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.AutoUnisolation
          operator: isEqualString
          right:
            value:
              simple: 'true'
      label: yes
    id: '18'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - '5'
      yes:
      - '12'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: ca3c5d6a-47b9-4786-82b6-e420527a5487
      iscommand: false
      name: Auto-Unisolate?
      description: Check if auto-unisolation is spesified.
      type: condition
      version: -1
    taskid: ca3c5d6a-47b9-4786-82b6-e420527a5487
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -120,
          "y": 200
        }
      }
  '51':
    id: '51'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '4'
      - '9'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 28ce0521-2635-4c6b-8e96-a49bb67c73c2
      iscommand: false
      name: False Positive
      type: title
      version: -1
      description: ''
    taskid: 28ce0521-2635-4c6b-8e96-a49bb67c73c2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 110,
          "y": -90
        }
      }
  '53':
    id: '53'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '60'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: e575ee22-5b49-4061-8640-1f01964e73a0
      iscommand: false
      name: Final Closure
      type: title
      version: -1
      description: ''
    taskid: e575ee22-5b49-4061-8640-1f01964e73a0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 120,
          "y": 870
        }
      }
  '60':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.DupAlertIDsToBeClosed
          operator: isNotEmpty
          right:
            value: {}
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.CloseDuplicate
          operator: containsString
          right:
            value:
              simple: close
      label: yes
    id: '60'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - '2'
      yes:
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: a8771130-3ba3-4816-8c39-445bc9a7460a
      iscommand: false
      name: Close duplicated alerts?
      description: Checks if you have duplicated alerts that have been closed in
      type: condition
      version: -1
    taskid: a8771130-3ba3-4816-8c39-445bc9a7460a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 120,
          "y": 1000
        }
      }
  '67':
    id: '67'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: Allowed
      indicator_description:
        simple: 'Added by Cortex XSOAR - Incident #${incident.id}'
      indicator_title:
        simple: 'Added by Cortex XSOAR - Incident #${incident.id} '
      indicator_type:
        simple: FileSha256
      indicator_value:
        simple: ${Indicators to Allow.Answers.0}
      severity:
        simple: Informational
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Creates a new indicator.
      id: d8c20f23-6974-418f-8b99-9d26e80ca4b8
      iscommand: true
      name: Create IOC on Microsoft Defender For Endpoint
      script: '|||microsoft-atp-sc-indicator-create'
      type: regular
      version: -1
    taskid: d8c20f23-6974-418f-8b99-9d26e80ca4b8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 780,
          "y": 550
        }
      }
  '68':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Indicators to Allow.Answers.0
          operator: isNotEmpty
      label: yes
    id: '68'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - '16'
      yes:
      - '15'
      - '67'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 93fa13d7-eb94-4160-83bf-a25b92905f20
      iscommand: false
      name: Was any hash selected?
      description: Check if there was any selected item from communication task.
      type: condition
      version: -1
    taskid: 93fa13d7-eb94-4160-83bf-a25b92905f20
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 560,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1950,
        "width": 1570,
        "x": -410,
        "y": -220
      }
    }
  }
tests:
- Microsoft Defender Advanced Threat Protection - Test
- Microsoft Defender - ATP - Indicators SC Test
fromversion: 6.2.0
